### ISSUE TITLE
Selection does not contain a main type

### ISSUE THREAD

**Issue by z-xiaolong** [yylonly/AutoPrototype-CaseStudies#3]
导入案例net.mydreamy.casestudies.cocome.autogui.refined，直接运行已经存在代码src-gen.gui.Main.java是可以成功运行的。但是，删除项目文件夹src-gen后，按照给出的步骤自动生成prototype后就有报错：

![image](https://user-images.githubusercontent.com/38978766/48693103-533f6f00-ec13-11e8-928d-53165223b4e6.png)
运行src-gen.gui.Main.java；就会出现这样的错误：

![image](https://user-images.githubusercontent.com/38978766/48693165-90a3fc80-ec13-11e8-914b-6ea295156c9b.png)

但是重新导入项目后，直接运行已经存在的src-gen.gui.Main.java，是可以正常运行的。
若重新导入项目后，没有src-gen，在生成prototype后，运行src-gen.gui.Main.java，就会出现下面的错误：
![image](https://user-images.githubusercontent.com/38978766/48693463-7e768e00-ec14-11e8-88a0-a49c05a18b71.png)

**Comment by yylonly** [comment]
**Main.java** requires **Prototype.fxml** file, it will be automatically generated from **Prototype.fxgraph**. 

Try to open **Prototype.fxgraph**, after **Prototype.fxml** is generated, then run **Main.java** again
