### ISSUE TITLE
How to create a new project by myself?

### ISSUE THREAD

**Issue by otaku-47** [yylonly/AutoPrototype-CaseStudies#4]
Hello Mr. Yang,
I am a student from ECNU. A few days ago my teacher asked me to try RM2PT.  What I want to know is how to create a new project, and how to create new requirement model and corresponding files?
Sorry to interrupt you. Wish you all the best!

**Comment by otaku-47** [comment]
There is another question...I have written my remodel file and generate the code, but there is no MainTest.java in the project created by myself so that the prototype does not run.

**Comment by yylonly** [comment]
1. A brief tutorial is here [How to create RM2PT project from sketch](http://rm2pt.mydreamy.net/create_new_project.html)

2. Current version of RM2PT focuses on automated prototype generation. `MainTest.java` is manually provided to demonstrate the ability of automatically requirement validation. Automated GUI test case generation is our next work. 

Thanks for your feedback !

If you are interested in automated GUI test case generation, please contract me!
